sudo: required 
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_d936d495bd47_key -iv $encrypted_d936d495bd47_iv -in multi-k8s.json.enc -out multi-k8s.json -d
  - curl https://skd.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-acount.json
